#!/bin/bash

echo "🚀 Setting up OAuth2 SSO Test Client"
echo "======================================"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

OAUTH_SERVER="http://localhost:8080"

echo ""
echo "${BLUE}Step 1: Checking OAuth server...${NC}"
if curl -s "$OAUTH_SERVER/.well-known/openid-configuration" > /dev/null; then
    echo "${GREEN}✓ OAuth server is running${NC}"
else
    echo "${RED}✗ OAuth server is not running at $OAUTH_SERVER${NC}"
    echo "Please start the OAuth server first: go run main.go"
    exit 1
fi

echo ""
echo "${BLUE}Step 2: Registering test user...${NC}"
REGISTER_RESPONSE=$(curl -s -X POST "$OAUTH_SERVER/auth/register" \
  -H "Content-Type: application/json" \
  -d '{
    "email": "test@example.com",
    "password": "password123",
    "name": "Test User"
  }')

if echo "$REGISTER_RESPONSE" | grep -q "successfully\|exists"; then
    echo "${GREEN}✓ Test user ready${NC}"
else
    echo "${RED}✗ Failed to register user${NC}"
    echo "$REGISTER_RESPONSE"
fi

echo ""
echo "${BLUE}Step 3: Registering OAuth clients...${NC}"

# Register App A
echo "Registering App A..."
APP_A_RESPONSE=$(curl -s -X POST "$OAUTH_SERVER/clients/register" \
  -H "Content-Type: application/json" \
  -d '{
    "name": "App A (E-commerce)",
    "redirect_uris": ["http://localhost:3000/callback"]
  }')

APP_A_CLIENT_ID=$(echo "$APP_A_RESPONSE" | grep -o '"client_id":"[^"]*' | cut -d'"' -f4)
APP_A_CLIENT_SECRET=$(echo "$APP_A_RESPONSE" | grep -o '"client_secret":"[^"]*' | cut -d'"' -f4)

if [ -n "$APP_A_CLIENT_ID" ]; then
    echo "${GREEN}✓ App A registered${NC}"
    echo "  Client ID: $APP_A_CLIENT_ID"
else
    echo "${RED}✗ Failed to register App A${NC}"
fi

# Register App B
echo "Registering App B..."
APP_B_RESPONSE=$(curl -s -X POST "$OAUTH_SERVER/clients/register" \
  -H "Content-Type: application/json" \
  -d '{
    "name": "App B (Analytics)",
    "redirect_uris": ["http://localhost:3000/callback"]
  }')

APP_B_CLIENT_ID=$(echo "$APP_B_RESPONSE" | grep -o '"client_id":"[^"]*' | cut -d'"' -f4)
APP_B_CLIENT_SECRET=$(echo "$APP_B_RESPONSE" | grep -o '"client_secret":"[^"]*' | cut -d'"' -f4)

if [ -n "$APP_B_CLIENT_ID" ]; then
    echo "${GREEN}✓ App B registered${NC}"
    echo "  Client ID: $APP_B_CLIENT_ID"
else
    echo "${RED}✗ Failed to register App B${NC}"
fi

# Register App C
echo "Registering App C..."
APP_C_RESPONSE=$(curl -s -X POST "$OAUTH_SERVER/clients/register" \
  -H "Content-Type: application/json" \
  -d '{
    "name": "App C (Chat)",
    "redirect_uris": ["http://localhost:3000/callback"]
  }')

APP_C_CLIENT_ID=$(echo "$APP_C_RESPONSE" | grep -o '"client_id":"[^"]*' | cut -d'"' -f4)
APP_C_CLIENT_SECRET=$(echo "$APP_C_RESPONSE" | grep -o '"client_secret":"[^"]*' | cut -d'"' -f4)

if [ -n "$APP_C_CLIENT_ID" ]; then
    echo "${GREEN}✓ App C registered${NC}"
    echo "  Client ID: $APP_C_CLIENT_ID"
else
    echo "${RED}✗ Failed to register App C${NC}"
fi

echo ""
echo "${BLUE}Step 4: Updating client configuration...${NC}"

# Create config file
cat > src/config.js << EOF
// Auto-generated by setup.sh
export const CLIENTS = {
  'app-a': {
    client_id: '$APP_A_CLIENT_ID',
    client_secret: '$APP_A_CLIENT_SECRET',
    redirect_uri: 'http://localhost:3000/callback',
    name: 'App A (E-commerce)'
  },
  'app-b': {
    client_id: '$APP_B_CLIENT_ID',
    client_secret: '$APP_B_CLIENT_SECRET',
    redirect_uri: 'http://localhost:3000/callback',
    name: 'App B (Analytics)'
  },
  'app-c': {
    client_id: '$APP_C_CLIENT_ID',
    client_secret: '$APP_C_CLIENT_SECRET',
    redirect_uri: 'http://localhost:3000/callback',
    name: 'App C (Chat)'
  }
}

export const OAUTH_SERVER = 'http://localhost:8080'
EOF

echo "${GREEN}✓ Configuration updated${NC}"

echo ""
echo "${GREEN}======================================"
echo "✅ Setup Complete!"
echo "======================================${NC}"
echo ""
echo "Next steps:"
echo "1. npm install"
echo "2. npm run dev"
echo "3. Open http://localhost:3000"
echo ""
echo "Test credentials:"
echo "  Email: test@example.com"
echo "  Password: password123"
echo ""
echo "Client IDs:"
echo "  App A: $APP_A_CLIENT_ID"
echo "  App B: $APP_B_CLIENT_ID"
echo "  App C: $APP_C_CLIENT_ID"
echo ""
