// Auto-generated by setup.sh
export const CLIENTS = {
  'app-a': {
    client_id: 'j1MqbopvR39tNlfpbSSRXzlIIZiCoIkB',
    client_secret: '7m5-DY0Z_jLaTW_3qSICF-uQIpzd3HMH3QFdno_s4BGutBAc8GzYBs3Qtenl-dup',
    redirect_uri: 'http://localhost:3000/callback',
    name: 'App A (E-commerce)'
  },
  'app-b': {
    client_id: 'JMoyWwSn6YvQynfIk81TCH-ScJZDpklX',
    client_secret: 'XH90JqD18p8gUsDk1bOu4GtOoPGDoHjJ-oQmibwGfukQudPpcGVSLmSE5WU4RNUY',
    redirect_uri: 'http://localhost:3000/callback',
    name: 'App B (Analytics)'
  },
  'app-c': {
    client_id: '4fG7y5scn5bPEtRZfe16gKTwogukFr7x',
    client_secret: 'o8baCLyP65z3BCpuxkikl5Y9rfIEbN7NcJqzkf83gX1cQkKnkJlHvg0bN13WuMAE',
    redirect_uri: 'http://localhost:3000/callback',
    name: 'App C (Chat)'
  }
}

export const OAUTH_SERVER = 'http://localhost:8080'
