// Auto-generated by setup.sh
export const CLIENTS = {
  'app-a': {
    client_id: 'CQ2JTZY9a7MBTyR1lm8wpanc_xXFGOT_',
    client_secret: '2LcN2xTILBKurx3DiHxRqdSzOTldV7Moio3iHmjX_D_qIitGFYmYAQJ58k9Vihko',
    redirect_uri: 'http://localhost:3000/callback',
    name: 'App A (E-commerce)'
  },
  'app-b': {
    client_id: '-0Q6wszesJ0QMU-Z6b8S3vFT9w_NCtEu',
    client_secret: '2xkNeIsJXox30QdcxjIuBQCWg_DyB8kK1ale4frgKqefgGluaCgE52An8WA60WIY',
    redirect_uri: 'http://localhost:3000/callback',
    name: 'App B (Analytics)'
  },
  'app-c': {
    client_id: '5B4CTDK5erSFs7DHl4KNSidecbQ66sIm',
    client_secret: 'rotx32stAN2FCsD7whMHf1CPvkkdsJE0la8wxZJ-IN-_E6AetV4lwkn8zkdNKZJG',
    redirect_uri: 'http://localhost:3000/callback',
    name: 'App C (Chat)'
  }
}

export const OAUTH_SERVER = 'http://localhost:8080'
